# Generated by Django 3.0.6 on 2020-10-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0002_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
