# Generated by Django 3.0.6 on 2020-11-07 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0005_restaurant_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='leavingtime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 7)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 22, 42, 729849)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 22, 42, 729849)),
        ),
    ]
