# Generated by Django 3.0.6 on 2020-11-07 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0009_auto_20201107_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 8, 4, 791531)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 8, 4, 791531)),
        ),
    ]
