# Generated by Django 3.0.6 on 2020-11-07 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0010_auto_20201107_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='available',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 9, 35, 469522)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(17, 9, 35, 469522)),
        ),
    ]
