# Generated by Django 3.0.6 on 2020-11-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0011_auto_20201107_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='otp',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 8)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 59, 24, 700330)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(20, 59, 24, 700330)),
        ),
    ]
