# Generated by Django 3.0.6 on 2020-11-08 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0012_auto_20201108_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 4, 19, 279107)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(21, 4, 19, 279107)),
        ),
    ]
