# Generated by Django 3.0.6 on 2020-11-08 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0014_auto_20201108_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantphotos',
            name='ptype',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('FOOD', 'FOOD')], default='NORMAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2020, 11, 9)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 10, 12, 761611)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 10, 12, 761611)),
        ),
    ]
