# Generated by Django 3.0.6 on 2020-11-09 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantReservation', '0015_auto_20201109_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 57, 24, 846823)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 57, 24, 846823)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
